swagger: "2.0"
info: {}
basePath: /open
paths:
  /logFile/listFile:
    post:
      tags:
      - logFile
  /logFile/startTail:
    post:
      tags:
      - logFile
  /logFile/stopTail:
    post:
      tags:
      - logFile
